### ISSUE TITLE
How to use it with other Libraries that has color extension?

### ISSUE THREAD

**Issue by kuwaitbinary** [mkj-is/MKJIcons#4]
Hello, Thank you for the wonderful library but I got a question if you can help, please

How to use is with this library I keep getting colors conflict

[https://github.com/bennyguitar/Colours](url)

**Comment by mkj-is** [comment]
> How to use is with this library I keep getting colors conflict

Usually when frameworks have conflicting extensions, the problem can be quite hard to solve but there are few solutions:

- https://stackoverflow.com/questions/33892897/name-collisions-for-extension-methods-from-different-frameworks
- https://stackoverflow.com/questions/32736698/swift-extension-same-extension-function-in-two-modules

I installed the latest version of MKJIcons using Swift package manager and Colours using CocoaPods (Objective-C version, the Swift one is in Swift 3.0 which is incompatible with current Xcode). I could get any conflicts and everything worked fine.

If you can provide exact conflicting methods or properties that are causing issues for you I can look into the problem.

Until then I am closing this issue, since this is not exactly issue of this framework. It is more in maintenance mode than in active development.
